const express = require('express')
const app = express()
const cors = require('cors')
const connect = require('./db/connect')
const http = require("http")
require('dotenv').config()
app.use(express.json())
connect()
const usersRouter = require('./routes/usersRouter')
app.use(cors())
app.use(usersRouter);
console.log(process.env)
app.listen(process.env.PORT, () => {
  console.log(`Example app listening on port ${process.env.PORT}`)
}) 